// Comprehensive car makes and models database
export const carMakes: Record<string, string[]> = {
  // American
  'Acura': ['CL', 'ILX', 'Integra', 'Legend', 'MDX', 'NSX', 'RDX', 'RL', 'RLX', 'RSX', 'SLX', 'TL', 'TLX', 'TSX', 'Vigor', 'ZDX'],
  'AMC': ['Ambassador', 'AMX', 'Concord', 'Eagle', 'Gremlin', 'Hornet', 'Javelin', 'Matador', 'Pacer', 'Rambler', 'Spirit'],
  'Buick': ['Cascada', 'Century', 'Electra', 'Enclave', 'Encore', 'Encore GX', 'Envision', 'Envista', 'Grand National', 'LaCrosse', 'LeSabre', 'Lucerne', 'Park Avenue', 'Rainier', 'Reatta', 'Regal', 'Rendezvous', 'Riviera', 'Roadmaster', 'Skylark', 'Terraza', 'Verano', 'Wildcat'],
  'Cadillac': ['Allante', 'ATS', 'Brougham', 'Catera', 'CTS', 'CT4', 'CT5', 'CT6', 'DeVille', 'DTS', 'Eldorado', 'ELR', 'Escalade', 'Escalade ESV', 'Escalade EXT', 'Fleetwood', 'Lyriq', 'Seville', 'SRX', 'STS', 'XLR', 'XT4', 'XT5', 'XT6', 'XTS'],
  'Chevrolet': ['Astro', 'Avalanche', 'Aveo', 'Bel Air', 'Beretta', 'Blazer', 'Bolt EV', 'Bolt EUV', 'Camaro', 'Caprice', 'Captiva', 'Cavalier', 'Celebrity', 'Chevelle', 'Chevette', 'Citation', 'City Express', 'Cobalt', 'Colorado', 'Corsica', 'Corvair', 'Corvette', 'Cruze', 'El Camino', 'Equinox', 'Express', 'HHR', 'Impala', 'Kodiak', 'Lumina', 'Malibu', 'Metro', 'Monte Carlo', 'Nova', 'Optra', 'Orlando', 'Prizm', 'S-10', 'Silverado 1500', 'Silverado 2500', 'Silverado 3500', 'Sonic', 'Spark', 'SS', 'SSR', 'Suburban', 'Tahoe', 'Tracker', 'TrailBlazer', 'Traverse', 'Trax', 'Uplander', 'Vega', 'Venture', 'Volt'],
  'Chrysler': ['200', '300', '300C', '300M', 'Aspen', 'Cirrus', 'Concorde', 'Conquest', 'Cordoba', 'Crossfire', 'Fifth Avenue', 'Imperial', 'Intrepid', 'LeBaron', 'LHS', 'Nassau', 'New Yorker', 'Newport', 'Pacifica', 'Prowler', 'PT Cruiser', 'Sebring', 'TC', 'Town & Country', 'Voyager'],
  'DeLorean': ['DMC-12'],
  'Dodge': ['Avenger', 'Caliber', 'Caravan', 'Challenger', 'Charger', 'Colt', 'D150', 'D250', 'Dakota', 'Dart', 'Daytona', 'Demon', 'Diplomat', 'Durango', 'Dynasty', 'Grand Caravan', 'Hornet', 'Intrepid', 'Journey', 'Lancer', 'Magnum', 'Monaco', 'Neon', 'Nitro', 'Omni', 'Polara', 'Power Wagon', 'Raider', 'Ram 1500', 'Ram 2500', 'Ram 3500', 'Ram Van', 'Shadow', 'Spirit', 'Sprinter', 'Stealth', 'Stratus', 'Viper'],
  'Eagle': ['Premier', 'Summit', 'Talon', 'Vision'],
  'Ford': ['Aerostar', 'Aspire', 'Bronco', 'Bronco II', 'Bronco Sport', 'C-Max', 'Contour', 'Crown Victoria', 'E-150', 'E-250', 'E-350', 'EcoSport', 'Edge', 'Escape', 'Escort', 'Excursion', 'Expedition', 'Explorer', 'Explorer Sport Trac', 'F-100', 'F-150', 'F-150 Lightning', 'F-250', 'F-350', 'F-450', 'Fairlane', 'Fairmont', 'Falcon', 'Festiva', 'Fiesta', 'Five Hundred', 'Flex', 'Focus', 'Freestar', 'Freestyle', 'Fusion', 'Galaxie', 'Granada', 'GT', 'LTD', 'Maverick', 'Model A', 'Model T', 'Mustang', 'Mustang Mach-E', 'Pinto', 'Probe', 'Ranger', 'Ranchero', 'Taurus', 'Tempo', 'Thunderbird', 'Torino', 'Transit', 'Transit Connect', 'Windstar'],
  'Geo': ['Metro', 'Prizm', 'Spectrum', 'Storm', 'Tracker'],
  'GMC': ['Acadia', 'Canyon', 'Envoy', 'Hummer EV', 'Jimmy', 'Safari', 'Savana', 'Sierra 1500', 'Sierra 2500', 'Sierra 3500', 'Sonoma', 'Suburban', 'Syclone', 'Terrain', 'Typhoon', 'Vandura', 'Yukon', 'Yukon XL'],
  'Hummer': ['H1', 'H2', 'H3', 'H3T'],
  'Jeep': ['Cherokee', 'CJ-5', 'CJ-7', 'CJ-8', 'Commander', 'Comanche', 'Compass', 'Gladiator', 'Grand Cherokee', 'Grand Cherokee L', 'Grand Wagoneer', 'J-10', 'J-20', 'Liberty', 'Patriot', 'Renegade', 'Scrambler', 'Wagoneer', 'Wrangler', 'Wrangler Unlimited'],
  'Lincoln': ['Aviator', 'Blackwood', 'Continental', 'Corsair', 'LS', 'Mark LT', 'Mark VII', 'Mark VIII', 'MKC', 'MKS', 'MKT', 'MKX', 'MKZ', 'Nautilus', 'Navigator', 'Town Car', 'Zephyr'],
  'Mercury': ['Capri', 'Cougar', 'Grand Marquis', 'Lynx', 'Marauder', 'Mariner', 'Milan', 'Montego', 'Monterey', 'Mountaineer', 'Mystique', 'Sable', 'Topaz', 'Tracer', 'Villager'],
  'Oldsmobile': ['88', '98', 'Achieva', 'Alero', 'Aurora', 'Bravada', 'Calais', 'Ciera', 'Cutlass', 'Cutlass Ciera', 'Cutlass Supreme', 'Delta 88', 'Intrigue', 'LSS', 'Regency', 'Silhouette', 'Toronado'],
  'Plymouth': ['Acclaim', 'Barracuda', 'Breeze', 'Colt', 'Cuda', 'Duster', 'Fury', 'Grand Voyager', 'GTX', 'Horizon', 'Laser', 'Neon', 'Prowler', 'Reliant', 'Road Runner', 'Satellite', 'Sundance', 'Valiant', 'Voyager'],
  'Pontiac': ['Aztek', 'Bonneville', 'Catalina', 'Fiero', 'Firebird', 'G3', 'G5', 'G6', 'G8', 'Grand Am', 'Grand Prix', 'GTO', 'LeMans', 'Montana', 'Solstice', 'Sunbird', 'Sunfire', 'Tempest', 'Torrent', 'Trans Am', 'Trans Sport', 'Vibe'],
  'Ram': ['1500', '1500 Classic', '2500', '3500', 'ProMaster', 'ProMaster City'],
  'Saturn': ['Astra', 'Aura', 'Ion', 'L100', 'L200', 'L300', 'LS', 'LW', 'Outlook', 'Relay', 'SC', 'SC1', 'SC2', 'Sky', 'SL', 'SL1', 'SL2', 'SW', 'Vue'],
  'Shelby': ['Cobra', 'GT350', 'GT500'],
  'Studebaker': ['Avanti', 'Champion', 'Commander', 'Hawk', 'Lark', 'President'],

  // Japanese
  'Honda': ['Accord', 'Accord Crosstour', 'Civic', 'Clarity', 'CR-V', 'CR-Z', 'Crosstour', 'CRX', 'Del Sol', 'Element', 'Fit', 'HR-V', 'Insight', 'Integra', 'Odyssey', 'Passport', 'Pilot', 'Prelude', 'Prologue', 'Ridgeline', 'S2000'],
  'Infiniti': ['EX35', 'EX37', 'FX35', 'FX37', 'FX45', 'FX50', 'G20', 'G25', 'G35', 'G37', 'I30', 'I35', 'J30', 'JX35', 'M30', 'M35', 'M37', 'M45', 'M56', 'Q40', 'Q45', 'Q50', 'Q60', 'Q70', 'QX4', 'QX30', 'QX50', 'QX55', 'QX56', 'QX60', 'QX70', 'QX80'],
  'Isuzu': ['Amigo', 'Ascender', 'Axiom', 'Hombre', 'I-280', 'I-290', 'I-350', 'I-370', 'Impulse', 'Oasis', 'Pickup', 'Rodeo', 'Rodeo Sport', 'Stylus', 'Trooper', 'VehiCROSS'],
  'Lexus': ['CT200h', 'ES250', 'ES300', 'ES300h', 'ES330', 'ES350', 'GS200t', 'GS300', 'GS350', 'GS400', 'GS430', 'GS450h', 'GS460', 'GS F', 'GX460', 'GX470', 'GX550', 'HS250h', 'IS200t', 'IS250', 'IS300', 'IS350', 'IS500', 'IS F', 'LC500', 'LC500h', 'LFA', 'LS400', 'LS430', 'LS460', 'LS500', 'LS500h', 'LS600h', 'LX450', 'LX470', 'LX570', 'LX600', 'NX200t', 'NX250', 'NX300', 'NX300h', 'NX350', 'NX350h', 'NX450h+', 'RC200t', 'RC300', 'RC350', 'RC F', 'RX300', 'RX330', 'RX350', 'RX350h', 'RX400h', 'RX450h', 'RX450h+', 'RX500h', 'RZ450e', 'SC300', 'SC400', 'SC430', 'TX350', 'TX500h', 'TX550h+', 'UX200', 'UX250h', 'UX300e'],
  'Mazda': ['2', '3', '5', '6', '323', '626', '929', 'B2000', 'B2200', 'B2300', 'B2500', 'B2600', 'B3000', 'B4000', 'CX-3', 'CX-30', 'CX-5', 'CX-50', 'CX-7', 'CX-9', 'CX-90', 'GLC', 'Mazdaspeed3', 'Mazdaspeed6', 'Millenia', 'MPV', 'MX-3', 'MX-5 Miata', 'MX-6', 'MX-30', 'Navajo', 'Protege', 'Protege5', 'RX-7', 'RX-8', 'Tribute'],
  'Mitsubishi': ['3000GT', 'Cordia', 'Diamante', 'Eclipse', 'Eclipse Cross', 'Endeavor', 'Expo', 'Galant', 'i-MiEV', 'Lancer', 'Lancer Evolution', 'Mighty Max', 'Mirage', 'Mirage G4', 'Montero', 'Montero Sport', 'Outlander', 'Outlander PHEV', 'Outlander Sport', 'Precis', 'Raider', 'Sigma', 'Starion', 'Tredia', 'Van'],
  'Nissan': ['200SX', '240SX', '240Z', '260Z', '280Z', '280ZX', '300ZX', '350Z', '370Z', 'Altima', 'Armada', 'Ariya', 'Axxess', 'Cube', 'Frontier', 'GT-R', 'Juke', 'Kicks', 'Leaf', 'Maxima', 'Murano', 'NV200', 'NV Cargo', 'NV Passenger', 'NX', 'Pathfinder', 'Pickup', 'Pulsar', 'Quest', 'Rogue', 'Rogue Select', 'Rogue Sport', 'Sentra', 'Stanza', 'Titan', 'Titan XD', 'Versa', 'Versa Note', 'Xterra', 'Z'],
  'Scion': ['FR-S', 'iA', 'iM', 'iQ', 'tC', 'xA', 'xB', 'xD'],
  'Subaru': ['Ascent', 'B9 Tribeca', 'Baja', 'BRZ', 'Crosstrek', 'Forester', 'Impreza', 'Impreza WRX', 'Justy', 'Legacy', 'Loyale', 'Outback', 'Solterra', 'SVX', 'Tribeca', 'WRX', 'XT', 'XV Crosstrek'],
  'Suzuki': ['Aerio', 'Equator', 'Esteem', 'Forenza', 'Grand Vitara', 'Kizashi', 'Reno', 'Samurai', 'Sidekick', 'Swift', 'SX4', 'Verona', 'Vitara', 'X-90', 'XL7'],
  'Toyota': ['4Runner', '86', 'Avalon', 'bZ4X', 'C-HR', 'Camry', 'Celica', 'Corolla', 'Corolla Cross', 'Corolla iM', 'Corona', 'Cressida', 'Crown', 'Crown Signia', 'Echo', 'FJ Cruiser', 'Grand Highlander', 'GR86', 'GR Corolla', 'GR Supra', 'Highlander', 'Land Cruiser', 'Matrix', 'Mirai', 'MR2', 'MR2 Spyder', 'Paseo', 'Pickup', 'Previa', 'Prius', 'Prius c', 'Prius Prime', 'Prius v', 'RAV4', 'RAV4 Prime', 'Sequoia', 'Sienna', 'Solara', 'Starlet', 'Supra', 'T100', 'Tacoma', 'Tercel', 'Tundra', 'Venza', 'Yaris', 'Yaris iA'],

  // Korean
  'Genesis': ['Electrified G80', 'Electrified GV70', 'G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80'],
  'Hyundai': ['Accent', 'Azera', 'Elantra', 'Elantra GT', 'Elantra N', 'Entourage', 'Equus', 'Excel', 'Genesis', 'Genesis Coupe', 'Ioniq', 'Ioniq 5', 'Ioniq 5 N', 'Ioniq 6', 'Kona', 'Kona Electric', 'Kona N', 'Nexo', 'Palisade', 'Santa Cruz', 'Santa Fe', 'Santa Fe Sport', 'Scoupe', 'Sonata', 'Tiburon', 'Tucson', 'Veloster', 'Veloster N', 'Venue', 'Veracruz', 'XG300', 'XG350'],
  'Kia': ['Amanti', 'Borrego', 'Cadenza', 'Carnival', 'Clarus', 'EV6', 'EV9', 'Forte', 'Forte Koup', 'K5', 'K900', 'Mentor', 'Niro', 'Niro EV', 'Optima', 'Rondo', 'Rio', 'Sedona', 'Seltos', 'Sephia', 'Sorento', 'Soul', 'Soul EV', 'Spectra', 'Sportage', 'Stinger', 'Telluride'],

  // German
  'Audi': ['80', '90', '100', '200', '4000', '5000', 'A3', 'A4', 'A4 allroad', 'A5', 'A6', 'A6 allroad', 'A7', 'A8', 'allroad', 'Cabriolet', 'Coupe', 'e-tron', 'e-tron GT', 'e-tron S', 'e-tron S Sportback', 'e-tron Sportback', 'Q3', 'Q4 e-tron', 'Q4 Sportback e-tron', 'Q5', 'Q5 Sportback', 'Q6 e-tron', 'Q7', 'Q8', 'Q8 e-tron', 'Q8 Sportback e-tron', 'Quattro', 'R8', 'RS3', 'RS4', 'RS5', 'RS6', 'RS6 Avant', 'RS7', 'RS e-tron GT', 'RS Q8', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'SQ5', 'SQ5 Sportback', 'SQ7', 'SQ8', 'SQ8 e-tron', 'TT', 'TT RS', 'TTS', 'V8'],
  'BMW': ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series', '128i', '228i', '320i', '328i', '330i', '335i', '428i', '435i', '520i', '528i', '530i', '535i', '540i', '550i', '640i', '650i', '740i', '745i', '750i', '760i', '840i', '850i', 'ActiveHybrid', 'i3', 'i4', 'i5', 'i7', 'i8', 'iX', 'iX M60', 'iX xDrive50', 'M2', 'M3', 'M4', 'M5', 'M6', 'M8', 'X1', 'X2', 'X3', 'X3 M', 'X4', 'X4 M', 'X5', 'X5 M', 'X6', 'X6 M', 'X7', 'XM', 'Z3', 'Z4', 'Z8'],
  'Mercedes-Benz': ['190', '240D', '300', 'A-Class', 'AMG GT', 'AMG GT 4-Door', 'AMG ONE', 'B-Class', 'C-Class', 'CL-Class', 'CLA-Class', 'CLK-Class', 'CLS-Class', 'E-Class', 'EQA', 'EQB', 'EQC', 'EQE', 'EQE SUV', 'EQS', 'EQS SUV', 'G-Class', 'GL-Class', 'GLA-Class', 'GLB-Class', 'GLC-Class', 'GLC Coupe', 'GLE-Class', 'GLE Coupe', 'GLK-Class', 'GLS-Class', 'Maybach GLS', 'Maybach S-Class', 'Metris', 'ML-Class', 'R-Class', 'S-Class', 'SL-Class', 'SLC-Class', 'SLK-Class', 'SLR McLaren', 'SLS AMG', 'Sprinter'],
  'MINI': ['Clubman', 'Convertible', 'Countryman', 'Coupe', 'Hardtop', 'Hardtop 2 Door', 'Hardtop 4 Door', 'Paceman', 'Roadster'],
  'Porsche': ['356', '718 Boxster', '718 Cayman', '718 Spyder', '911', '911 Carrera', '911 GT2', '911 GT3', '911 Turbo', '918 Spyder', '924', '928', '944', '959', '968', 'Boxster', 'Carrera GT', 'Cayenne', 'Cayenne Coupe', 'Cayman', 'Macan', 'Panamera', 'Taycan', 'Taycan Cross Turismo'],
  'Smart': ['Fortwo', 'EQ fortwo'],
  'Volkswagen': ['Arteon', 'Atlas', 'Atlas Cross Sport', 'Beetle', 'Cabrio', 'Cabriolet', 'CC', 'Corrado', 'e-Golf', 'Eos', 'Eurovan', 'Fox', 'GLI', 'Golf', 'Golf Alltrack', 'Golf GTI', 'Golf R', 'Golf SportWagen', 'GTI', 'ID.4', 'ID.Buzz', 'Jetta', 'Jetta GLI', 'Karmann Ghia', 'Passat', 'Phaeton', 'R32', 'Rabbit', 'Routan', 'Scirocco', 'Taos', 'Thing', 'Tiguan', 'Touareg', 'Type 1', 'Type 2', 'Type 3', 'Vanagon'],

  // British
  'Aston Martin': ['DB7', 'DB9', 'DB11', 'DB12', 'DBS', 'DBS Superleggera', 'DBX', 'DBX707', 'Rapide', 'V8 Vantage', 'V12 Vantage', 'Vanquish', 'Vantage', 'Virage'],
  'Bentley': ['Arnage', 'Azure', 'Bentayga', 'Brooklands', 'Continental', 'Continental Flying Spur', 'Continental GT', 'Continental GTC', 'Flying Spur', 'Mulsanne'],
  'Jaguar': ['E-Pace', 'E-Type', 'F-Pace', 'F-Type', 'I-Pace', 'S-Type', 'XE', 'XF', 'XJ', 'XJR', 'XJS', 'XK', 'XK8', 'XKR', 'X-Type'],
  'Land Rover': ['Defender', 'Defender 90', 'Defender 110', 'Defender 130', 'Discovery', 'Discovery Sport', 'Freelander', 'LR2', 'LR3', 'LR4', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport', 'Range Rover Velar'],
  'Lotus': ['Elise', 'Emira', 'Esprit', 'Europa', 'Evija', 'Evora', 'Exige'],
  'McLaren': ['540C', '570GT', '570S', '600LT', '620R', '650S', '675LT', '720S', '750S', '765LT', 'Artura', 'Elva', 'GT', 'P1', 'Senna', 'Speedtail'],
  'Rolls-Royce': ['Corniche', 'Cullinan', 'Dawn', 'Ghost', 'Park Ward', 'Phantom', 'Silver Cloud', 'Silver Dawn', 'Silver Seraph', 'Silver Shadow', 'Silver Spirit', 'Silver Spur', 'Spectre', 'Wraith'],

  // Italian
  'Alfa Romeo': ['147', '156', '159', '164', '4C', '4C Spider', '8C Competizione', 'Giulia', 'Giulietta', 'GTV', 'MiTo', 'Spider', 'Stelvio', 'Tonale'],
  'Ferrari': ['208', '250', '275', '288 GTO', '296 GTB', '296 GTS', '308', '328', '348', '360', '365', '430 Scuderia', '458', '458 Italia', '458 Spider', '488', '488 GTB', '488 Pista', '488 Spider', '512', '550', '575M', '599', '612 Scaglietti', '812', '812 GTS', '812 Superfast', 'California', 'California T', 'Daytona', 'Dino', 'Enzo', 'F12berlinetta', 'F355', 'F40', 'F430', 'F50', 'F8 Tributo', 'FF', 'GTC4Lusso', 'LaFerrari', 'Mondial', 'Portofino', 'Portofino M', 'Purosangue', 'Roma', 'SF90 Stradale', 'Testarossa'],
  'Fiat': ['124 Spider', '500', '500 Abarth', '500c', '500e', '500L', '500X', 'Brava', 'Bravo', 'Coupe', 'Panda', 'Punto', 'Spider', 'Strada', 'X1/9'],
  'Lamborghini': ['350 GT', '400 GT', 'Aventador', 'Centenario', 'Countach', 'Diablo', 'Espada', 'Gallardo', 'Huracan', 'Islero', 'Jarama', 'Jalpa', 'LM002', 'Miura', 'Murcielago', 'Revuelto', 'Sian', 'Urus'],
  'Maserati': ['3200 GT', 'Coupe', 'Ghibli', 'GranCabrio', 'GranSport', 'GranTurismo', 'Grecale', 'Levante', 'MC20', 'Merak', 'Quattroporte', 'Spyder'],

  // Swedish
  'Saab': ['9-2X', '9-3', '9-4X', '9-5', '9-7X', '900', '9000'],
  'Volvo': ['240', '740', '760', '780', '850', '940', '960', 'C30', 'C40', 'C70', 'EX30', 'EX90', 'S40', 'S60', 'S70', 'S80', 'S90', 'V40', 'V50', 'V60', 'V70', 'V90', 'XC40', 'XC60', 'XC70', 'XC90'],
  'Polestar': ['1', '2', '3', '4'],

  // French
  'Bugatti': ['Centodieci', 'Chiron', 'Divo', 'EB110', 'La Voiture Noire', 'Veyron'],
  'Citroen': ['2CV', 'AX', 'BX', 'C3', 'C4', 'C5', 'CX', 'DS', 'DS3', 'DS4', 'DS5', 'SM', 'Xantia', 'XM', 'ZX'],
  'Peugeot': ['106', '205', '206', '207', '208', '306', '307', '308', '405', '406', '407', '408', '504', '505', '508', '604', '607', 'Partner', 'RCZ'],
  'Renault': ['5', '9', '11', '12', '15', '17', '18', '19', '21', '25', 'Alpine', 'Captur', 'Clio', 'Dauphine', 'Espace', 'Fuego', 'Kangoo', 'Koleos', 'Laguna', 'Megane', 'R5', 'Safrane', 'Scenic', 'Twingo', 'Zoe'],

  // Electric/EV Startups
  'Fisker': ['Karma', 'Ocean', 'Pear', 'Ronin'],
  'Lucid': ['Air', 'Air Dream', 'Air Grand Touring', 'Air Pure', 'Air Touring', 'Gravity'],
  'Rivian': ['R1S', 'R1T', 'R2', 'R3'],
  'Tesla': ['Cybertruck', 'Model 3', 'Model S', 'Model X', 'Model Y', 'Roadster', 'Semi'],
  'VinFast': ['VF 6', 'VF 7', 'VF 8', 'VF 9'],

  // Chinese
  'BYD': ['Atto 3', 'Dolphin', 'Han', 'Seal', 'Seagull', 'Song', 'Tang', 'Yuan'],
  'Geely': ['Coolray', 'Emgrand', 'GC9', 'Geometry', 'Icon', 'Jiaji', 'Xingyue'],
  'Great Wall': ['Cannon', 'Haval H6', 'Ora', 'Poer', 'Tank 300', 'Tank 500', 'Wey'],
  'NIO': ['EC6', 'ES6', 'ES7', 'ES8', 'ET5', 'ET7'],
  'XPeng': ['G3', 'G6', 'G9', 'P5', 'P7'],

  // Other
  'Daewoo': ['Espero', 'Lanos', 'Leganza', 'Nubira'],
  'Daihatsu': ['Charade', 'Rocky'],
  'Datsun': ['240Z', '260Z', '280Z', '280ZX', '510', '610', '710', '810', 'B210', 'F10', 'Maxima', 'Pickup', 'Pulsar', 'Sentra', 'Stanza', 'Z'],
  'Koenigsegg': ['Agera', 'CC8S', 'CCR', 'CCXR', 'Gemera', 'Jesko', 'One:1', 'Regera'],
  'Maybach': ['57', '62', 'Exelero'],
  'Pagani': ['Huayra', 'Zonda'],

  'Other': ['Other'],
};

export const carTypes = [
  'Sedan',
  'SUV',
  'Crossover',
  'Truck',
  'Pickup',
  'Coupe',
  'Convertible',
  'Hatchback',
  'Wagon',
  'Van',
  'Minivan',
  'Sports Car',
  'Supercar',
  'Hypercar',
  'Luxury',
  'Electric',
  'Hybrid',
  'Plug-in Hybrid',
  'Classic',
  'Vintage',
  'Muscle Car',
  'Hot Rod',
  'Off-Road',
  'Commercial',
  'Motorcycle',
  'Other',
];

export const years = Array.from({ length: 100 }, (_, i) => new Date().getFullYear() + 1 - i);

// Service categories for maintenance tracking
export const serviceCategories = [
  'Oil Change',
  'Tire Service',
  'Tire Rotation',
  'Tire Replacement',
  'Brake Service',
  'Brake Pads',
  'Brake Rotors',
  'Battery',
  'Air Filter',
  'Cabin Filter',
  'Spark Plugs',
  'Transmission Service',
  'Transmission Fluid',
  'Coolant Flush',
  'Power Steering',
  'Fuel System',
  'Fuel Filter',
  'Timing Belt',
  'Serpentine Belt',
  'Water Pump',
  'Alternator',
  'Starter',
  'AC Service',
  'Heating Service',
  'Suspension',
  'Shocks/Struts',
  'Alignment',
  'Exhaust',
  'Muffler',
  'Catalytic Converter',
  'Emissions',
  'Inspection',
  'Registration',
  'Insurance',
  'Detailing',
  'Car Wash',
  'Paint/Body',
  'Dent Repair',
  'Windshield',
  'Wiper Blades',
  'Lights/Bulbs',
  'Electrical',
  'Software Update',
  'Recall Service',
  'Warranty Work',
  'Roadside Assistance',
  'Towing',
  'Accident Repair',
  'Modification',
  'Performance Upgrade',
  'Other',
];
